### ISSUE TITLE
List websites I can publish paid tasks on

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Internship-project-tasks#34]
- https://gitpay.me/
- https://www.bountysource.com/

You can post on this ticket.

**Comment by abhhii** [comment]
Check these out :
beerpay.com
gitcoin.co

**Comment by jsxs0** [comment]
These should help.
- [https://folyo.me/](url)
- [https://issuehunt.io/](url)
- [https://gitcoin.co/](url)
- [https://www.hackerone.com/internet-bug-bounty](url)
- [https://www.ghostscript.com/Bug_bounty_program.html](url)
- [https://www.riscosopen.org/bounty/](url)
- [https://bountify.co/](url)
- [https://www.bountysource.com/](url)
- [https://www.bugcrowd.com/bug-bounty-list/](url)
- [http://www.hnhiring.me/](url)
Regards.

**Comment by ImprovedTube** [comment]
hi! @jsxs0 @abhhii
